### ISSUE TITLE
CallView improvements

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed-ios#1039]
After #997 and #1038 there are still some things left:

- [x] Check collectionView constraints. Currently constrained to safe area, which does not look nice when running on Mac. As far as I can see it looks good on iOS devices, so maybe just needs adjustments for Mac. Fixed in #1046
- [x] Fix #528. Fixed in #1047
- [x] Improve calculation of rows/cols (see `makeGrid` function in talk-web: https://github.com/nextcloud/spreed/blob/5ba554c3f751ba8b8035c7fc8404ca6194d3c16a/src/components/CallView/Grid/Grid.vue#L664). Done in https://github.com/nextcloud/talk-ios/pull/1056
- [x] Adjust the size of the AirPlay button. Fixed in #1049.
- [ ] #2363
- [x] Adjust the avatar size in `NCChatTitleView`. Fixed in #1045
- [x] Show a notification when recording is started (see https://github.com/nextcloud/spreed/issues/8324#issuecomment-1344070936). Fixed in https://github.com/nextcloud/talk-ios/pull/1063
- [x] Add `Force mute all` for moderators https://github.com/nextcloud/talk-ios/pull/2031
- [x] Add `End for all` for moderators #1237 
- [x] Check colors of participant cells again Fixed in https://github.com/nextcloud/talk-ios/pull/1062
- [x] Button to show a closed screenshare not visible anymore (but can be touched) Fixed in https://github.com/nextcloud/talk-ios/pull/1064
- [x] Avatar size needs to be adjusted for small cells (25 cells on iPad) Fixed in https://github.com/nextcloud/talk-ios/pull/1064
- [x] Label needs to be adjusted for small cells (see avatar size above) Fixed in https://github.com/nextcloud/talk-ios/pull/1064
